### PR TITLE
script for checking missing words

### PR DESCRIPTION
**Pull request by Cephas369**

### CODE REVIEW

**Comment by minenwerfer** [comment]
Please move `index.ts` to `scripts/check-missing-words.ts`, install `ts-node`, and setup a script in `package.json` to run it. 
Also replace the legacy `fs.readFile` callback with `await fs.promises.readFile`.

Also replace the `tsconfig.json` with a simpler one, like https://github.com/aeria-org/aeria/blob/master/tsconfig.json.

**Comment by Cephas369** [comment]
> Please move `index.ts` to `scripts/check-missing-words.ts`, install `ts-node`, and setup a script in `package.json` to run it. Also replace the legacy `fs.readFile` callback with `await fs.promises.readFile`.
> 
> Also replace the `tsconfig.json` with a simpler one, like https://github.com/aeria-org/aeria/blob/master/tsconfig.json.

Done

**Comment by minenwerfer** [comment]
> > Please move `index.ts` to `scripts/check-missing-words.ts`, install `ts-node`, and setup a script in `package.json` to run it. Also replace the legacy `fs.readFile` callback with `await fs.promises.readFile`.
> > Also replace the `tsconfig.json` with a simpler one, like https://github.com/aeria-org/aeria/blob/master/tsconfig.json.
> 
> Done

Hey, could you also pass the encoding as 'utf8' in the second argument of `readFile` instead of casting the return value to string later? Everything else seems okay to me now.

**Comment by Cephas369** [comment]
> > > Please move `index.ts` to `scripts/check-missing-words.ts`, install `ts-node`, and setup a script in `package.json` to run it. Also replace the legacy `fs.readFile` callback with `await fs.promises.readFile`.
> > > Also replace the `tsconfig.json` with a simpler one, like https://github.com/aeria-org/aeria/blob/master/tsconfig.json.
> > 
> > 
> > Done
> 
> Hey, could you also pass the encoding as 'utf8' in the second argument of `readFile` instead of casting the return value to string later? Everything else seems okay to me now.

Done too

**Pull request merged**
